import type { Metadata } from "next";
import { Rye ,Source_Sans_3} from "next/font/google";
import "./globals.css";
import Header from "./components/layout/header";
import Footer from "./components/layout/footer";

const rye = Rye({
  variable: "--font-rye",
  subsets: ["latin"],
  weight: "400",
})

const sans3 = Source_Sans_3({
  variable: "--font-source-sans-3",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rye.variable} ${sans3.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
